# Generated by Django 4.2.6 on 2023-10-13 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Invalid duration time')]),
        ),
    ]
